<html>
    <head>
        <script>
            function f0() {
                return new Promise((resolve, reject) => {
                    let x;
                    setTimeout(() => {
                        x = 100;
                        resolve(x);
                    }, 1000);
                });
            }

            function f1(x) {
                return new Promise((resolve, reject) => {
                    setTimeout(() => {
                        // resolve(x + 100)
                        reject("some error");
                    }, 2000);
                });
            }

            function f2(x) {
                return new Promise((resolve, reject) => {
                    setTimeout(() => {
                        resolve(x + 200);
                    }, 3000);
                });
            }

            f0()
                .then((result) => {
                    return f1(result);
                })
                .then((result) => {
                    return f2(result);
                })
                .then((result) => {
                    console.log(result);
                })
                .catch((err) => {
                    console.log(err);
                });

            const main = async () => {
                try {
                    let result = await f0();
                    console.log("before f1");
                    result = await f1(result);
                    console.log("after f1");
                    result = await f2(result);
                    console.log(result);
                } catch (error) {
                    console.warn(error);
                }
            };
        </script>
    </head>
</html>
